name: ECS Scaling

on:
  workflow_dispatch:
    inputs:
      name:  
        required: true
        type: choice
        default: upscale
        options:
          - upscale
          - downscale
jobs:
  scale:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1
      - name: Make the shell file exeutable
        run: chmod +x multi-ecs-scaling.sh
        
      - name: Scaling ECS
        run: ./multi-ecs-scaling.sh ${{inputs.name}} 
      












      
